// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALeG4a825tlxM-AxJ7bi9kccLt36SJ9K0',
    appId: '1:612583858973:web:794f82e68204c5147c37f4',
    messagingSenderId: '612583858973',
    projectId: 'fir-auth-4784b',
    authDomain: 'fir-auth-4784b.firebaseapp.com',
    storageBucket: 'fir-auth-4784b.appspot.com',
    measurementId: 'G-X8DPJ5667T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWNji3aYFHT8473bauEdgAaDVD7wDNso',
    appId: '1:612583858973:android:ae061cffb403a4117c37f4',
    messagingSenderId: '612583858973',
    projectId: 'fir-auth-4784b',
    storageBucket: 'fir-auth-4784b.appspot.com',
  );
}
